# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Noti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Noti
  pod ‘lottie-ios’

  target 'NotiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
